In [6]:
import numpy as np
import pandas as pd

In [7]:
books = pd.read_csv("Books.csv")
users = pd.read_csv("Users.csv")
ratings = pd.read_csv("Ratings.csv")

C:\Users\risha\AppData\Local\Temp\ipykernel_25372\2906776592.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("Books.csv")

In [8]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,2005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,60973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [9]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [10]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726   155061224            5
2   276727   446520802            0
3   276729  052165615X            3
4   276729   521795028            6

In [11]:
books.shape

(271360, 8)

In [12]:
users.shape

(278858, 3)

In [13]:
ratings.shape

(1048575, 3)

In [14]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [15]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [16]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [17]:
books.duplicated().sum()

np.int64(0)

In [18]:
users.duplicated().sum()

np.int64(0)

In [19]:
ratings.duplicated().sum()

np.int64(72)

In [20]:
ratings_duplicate = ratings[ratings.duplicated()]
print(ratings_duplicate)

         User-ID         ISBN  Book-Rating
21604       4334  6.30892E+11            0
28622       6575  6.30892E+11            0
58889      11676  9.78843E+12            0
59326      11795            0            7
59327      11795            0            0
...          ...          ...          ...
1047765   250634  9.78034E+12            0
1047766   250634  9.78034E+12           10
1047767   250634  9.78034E+12           10
1047768   250634  9.78034E+12           10
1047769   250634  9.78034E+12            0

[72 rows x 3 columns]

In [21]:
ratings.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1048570    False
1048571    False
1048572    False
1048573    False
1048574    False
Length: 1048575, dtype: bool

In [22]:
ratings = ratings.drop_duplicates()

In [23]:
ratings

         User-ID        ISBN  Book-Rating
0         276725  034545104X            0
1         276726   155061224            5
2         276727   446520802            0
3         276729  052165615X            3
4         276729   521795028            6
...          ...         ...          ...
1048570   250764   451410777            0
1048571   250764   452264464            8
1048572   250764  048623715X            0
1048573   250764   486256588            0
1048574   250764   515069434            0

[1048503 rows x 3 columns]

In [24]:
ratings.shape

(1048503, 3)

In [25]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,2005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,60973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [26]:
books['Book-Title'].value_counts() #Count of Books

Book-Title
Selected Poems                                                                27
Little Women                                                                  24
Wuthering Heights                                                             21
The Secret Garden                                                             20
Dracula                                                                       20
                                                                              ..
The Female Power Within: A Guide to Living a Gentler, More Meaningful Life     1
Christie's Collectables: Blue and White China (Christie's Collectables)        1
Schmatz. Oder Die Sackgasse.                                                   1
Amok.                                                                          1
Basic Scientific Subroutines                                                   1
Name: count, Length: 242131, dtype: int64

In [27]:
books['Book-Author'].value_counts()  #Count of authors with most number of books

Book-Author
Agatha Christie            632
William Shakespeare        567
Stephen King               524
Ann M. Martin              423
Carolyn Keene              373
                          ...
JÃ¶rn Kalkbrenner            1
Paul A. Lynn                 1
Arthur Bernard Williams      1
Fred Ruckdeschel             1
Glass Charles                1
Name: count, Length: 102022, dtype: int64

In [28]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726   155061224            5
2   276727   446520802            0
3   276729  052165615X            3
4   276729   521795028            6

In [29]:
ratings['ISBN'].value_counts()

ISBN
971880107     2263
316666343     1164
385504209      813
312195516      668
60928336       662
              ...
312152094        1
014054612X       1
048623715X       1
486256588        1
553527517        1
Name: count, Length: 322473, dtype: int64

In [30]:
ratings.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1048570    False
1048571    False
1048572    False
1048573    False
1048574    False
Length: 1048503, dtype: bool

In [31]:
books.groupby('Book-Title')['Book-Author'].count()

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    1
 Always Have Popsicles                                                                                        1
 Apple Magic (The Collector's series)                                                                         1
 Ask Lily (Young Women of Faith: Lily Series, Book 5)                                                         1
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   1
                                                                                                             ..
Ã?Â?lpiraten.                                                                                                 1
Ã?Â?rger mit Produkt X. Roman.                                                                                1
Ã?Â?sterlich leben.                                                                                           1
Ã?Â?stlich der Berge.                                                                                         1
Ã?Â?thique en toc                                                                                             1
Name: Book-Author, Length: 242131, dtype: int64

In [32]:
books['Publisher'].value_counts()

Publisher
Harlequin                          7535
Silhouette                         4220
Pocket                             3905
Ballantine Books                   3783
Bantam Books                       3646
                                   ...
Special Libraries Assn                1
Ediciones Fraile                      1
National Textbook Company             1
Lulu Publishing                       1
Scholastic (An Apple Paperback)       1
Name: count, Length: 16806, dtype: int64

In [33]:
users['Location'].value_counts()

Location
london, england, united kingdom              2506
toronto, ontario, canada                     2250
sydney, new south wales, australia           1744
melbourne, victoria, australia               1708
portland, oregon, usa                        1629
                                             ...
new lothrop, michigan, usa                      1
esplugas de llobregat, n/a, spain               1
baxter springs, kansas, usa                     1
gustow, mecklenburg-vorpommern, germany         1
san colombano al lambro, lombardia, italy       1
Name: count, Length: 57339, dtype: int64

In [34]:
agatha_books = books[books['Book-Author'] == 'Agatha Christie']
agatha_books  #All books by Agatha Christie

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1855,451200993,Sleeping Murder (Miss Marple Mysteries (Paperb...,Agatha Christie,2000,New American Library,http://images.amazon.com/images/P/0451200993.0...,http://images.amazon.com/images/P/0451200993.0...,http://images.amazon.com/images/P/0451200993.0...
2012,671555235,A Caribbean Mystery,Agatha Christie,1984,Pocket,http://images.amazon.com/images/P/0671555235.0...,http://images.amazon.com/images/P/0671555235.0...,http://images.amazon.com/images/P/0671555235.0...
2355,425173755,Murder on the Orient Express (Hercule Poirot M...,Agatha Christie,2000,Berkley Publishing Group,http://images.amazon.com/images/P/0425173755.0...,http://images.amazon.com/images/P/0425173755.0...,http://images.amazon.com/images/P/0425173755.0...
2356,451199871,The Body in the Library (Miss Marple Mysteries...,Agatha Christie,2000,Signet Book,http://images.amazon.com/images/P/0451199871.0...,http://images.amazon.com/images/P/0451199871.0...,http://images.amazon.com/images/P/0451199871.0...
2569,067170463X,Murder on the Orient Express,Agatha Christie,1978,Pocket Books,http://images.amazon.com/images/P/067170463X.0...,http://images.amazon.com/images/P/067170463X.0...,http://images.amazon.com/images/P/067170463X.0...
...,...,...,...,...,...,...,...,...
270319,2702400787,Le couteau sur la nuque,Agatha Christie,1979,Librairie des Champs-ElysÃ?Â©es,http://images.amazon.com/images/P/2702400787.0...,http://images.amazon.com/images/P/2702400787.0...,http://images.amazon.com/images/P/2702400787.0...
270519,671494538,ENDLESS NIGHT,Agatha Christie,1983,Pocket,http://images.amazon.com/images/P/0671494538.0...,http://images.amazon.com/images/P/0671494538.0...,http://images.amazon.com/images/P/0671494538.0...
271094,8427201079,El Misterio De Sittaford,Agatha Christie,0,Editorial Molino,http://images.amazon.com/images/P/8427201079.0...,http://images.amazon.com/images/P/8427201079.0...,http://images.amazon.com/images/P/8427201079.0...
271095,8427285280,Poirot en Egipto,Agatha Christie,1996,Downtown Book Center,http://images.amazon.com/images/P/8427285280.0...,http://images.amazon.com/images/P/8427285280.0...,http://images.amazon.com/images/P/8427285280.0...
271250,073943828X,Murder at the Manor (Mystery Guild Lost Classi...,Agatha Christie,1929,Dodd Mead &amp; Company,http://images.amazon.com/images/P/073943828X.0...,http://images.amazon.com/images/P/073943828X.0...,http://images.amazon.com/images/P/073943828X.0...

In [35]:
books['Publisher'].value_counts().head(5)   #Top 5 Publishers with most number of published books.

Publisher
Harlequin           7535
Silhouette          4220
Pocket              3905
Ballantine Books    3783
Bantam Books        3646
Name: count, dtype: int64

In [36]:
books['Year-Of-Publication'].value_counts().head(5)    #Top 5 years with most publications.

Year-Of-Publication
2002    13903
2001    13715
1999    13414
2000    13373
1998    12116
Name: count, dtype: int64

In [37]:
users['Location'].value_counts().head(10) #Top 10 locations with most users.

Location
london, england, united kingdom        2506
toronto, ontario, canada               2250
sydney, new south wales, australia     1744
melbourne, victoria, australia         1708
portland, oregon, usa                  1629
chicago, illinois, usa                 1526
seattle, washington, usa               1484
new york, new york, usa                1411
madrid, madrid, spain                  1400
vancouver, british columbia, canada    1359
Name: count, dtype: int64

## POPULARITY BASED RECOMMENDATION SYSTEM

In [38]:
ratings_with_name = ratings.merge(books, on = 'ISBN')

In [39]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
941100,250764,451410777,0,Sleep Tight (Onyx Book),Anne Frasier,2003,Onyx Books,http://images.amazon.com/images/P/0451410777.0...,http://images.amazon.com/images/P/0451410777.0...,http://images.amazon.com/images/P/0451410777.0...
941101,250764,452264464,8,Beloved (Plume Contemporary Fiction),Toni Morrison,1994,Plume,http://images.amazon.com/images/P/0452264464.0...,http://images.amazon.com/images/P/0452264464.0...,http://images.amazon.com/images/P/0452264464.0...
941102,250764,048623715X,0,Glamorous Movie Stars of the Thirties: Paper D...,Tom Tierney,1982,Dover Publications,http://images.amazon.com/images/P/048623715X.0...,http://images.amazon.com/images/P/048623715X.0...,http://images.amazon.com/images/P/048623715X.0...
941103,250764,486256588,0,Schiaparelli Fashion Review: Paper Dolls in Fu...,Tom Tierney,1988,Dover Publications,http://images.amazon.com/images/P/0486256588.0...,http://images.amazon.com/images/P/0486256588.0...,http://images.amazon.com/images/P/0486256588.0...
941104,250764,515069434,0,Lady Laughing Eyes (To Have and to Hold),Lee Damon,1984,Jove Books,http://images.amazon.com/images/P/0515069434.0...,http://images.amazon.com/images/P/0515069434.0...,http://images.amazon.com/images/P/0515069434.0...

In [40]:
ratings_with_name.groupby('Book-Title').count()

,User-ID,ISBN,Book-Rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
Book-Title,,,,,,,,,
"A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)",4,4,4,4,4,4,4,4,4
Always Have Popsicles,1,1,1,1,1,1,1,1,1
Apple Magic (The Collector's series),1,1,1,1,1,1,1,1,1
Beyond IBM: Leadership Marketing and Finance for the 1990s,1,1,1,1,1,1,1,1,1
Clifford Visita El Hospital (Clifford El Gran Perro Colorado),1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
Ã?Â?l- Connection.,1,1,1,1,1,1,1,1,1
Ã?Â?lpiraten.,2,2,2,2,2,2,2,2,2
Ã?Â?rger mit Produkt X. Roman.,4,4,4,4,4,4,4,4,4
Ã?Â?stlich der Berge.,2,2,2,2,2,2,2,2,2
Ã?Â?thique en toc,2,2,2,2,2,2,2,2,2

In [41]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [42]:
num_rating_df

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Beyond IBM: Leadership Marketing and Finance ...            1
4        Clifford Visita El Hospital (Clifford El Gran...            1
...                                                   ...          ...
230215                                 Ã?Â?l- Connection.            1
230216                                      Ã?Â?lpiraten.            2
230217                     Ã?Â?rger mit Produkt X. Roman.            4
230218                              Ã?Â?stlich der Berge.            2
230219                                  Ã?Â?thique en toc            2

[230220 rows x 2 columns]

In [43]:
num_rating_df.rename(columns={'Book-Rating':'num_ratings'}, inplace=True)

In [44]:
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Beyond IBM: Leadership Marketing and Finance ...            1
4        Clifford Visita El Hospital (Clifford El Gran...            1
...                                                   ...          ...
230215                                 Ã?Â?l- Connection.            1
230216                                      Ã?Â?lpiraten.            2
230217                     Ã?Â?rger mit Produkt X. Roman.            4
230218                              Ã?Â?stlich der Berge.            2
230219                                  Ã?Â?thique en toc            2

[230220 rows x 2 columns]

In [45]:
ratings_with_name['Book-Rating'] = pd.to_numeric(ratings_with_name['Book-Rating'], errors='coerce')

In [46]:
avg_rating_df = ratings_with_name.groupby('Book-Title', as_index=False)['Book-Rating'].mean()
avg_rating_df.rename(columns={'Book-Rating':'avg_ratings'}, inplace=True)
avg_rating_df

                                               Book-Title  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...         2.25
1                                   Always Have Popsicles         0.00
2                    Apple Magic (The Collector's series)         0.00
3        Beyond IBM: Leadership Marketing and Finance ...         0.00
4        Clifford Visita El Hospital (Clifford El Gran...         0.00
...                                                   ...          ...
230215                                 Ã?Â?l- Connection.         0.00
230216                                      Ã?Â?lpiraten.         0.00
230217                     Ã?Â?rger mit Produkt X. Roman.         5.25
230218                              Ã?Â?stlich der Berge.         4.00
230219                                  Ã?Â?thique en toc         4.00

[230220 rows x 2 columns]

In [47]:
popular_df = num_rating_df.merge(avg_rating_df, on='Book-Title')
popular_df

,Book-Title,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.25
1,Always Have Popsicles,1,0.00
2,Apple Magic (The Collector's series),1,0.00
3,Beyond IBM: Leadership Marketing and Finance ...,1,0.00
4,Clifford Visita El Hospital (Clifford El Gran...,1,0.00
...,...,...,...
230215,Ã?Â?l- Connection.,1,0.00
230216,Ã?Â?lpiraten.,2,0.00
230217,Ã?Â?rger mit Produkt X. Roman.,4,5.25
230218,Ã?Â?stlich der Berge.,2,4.00
230219,Ã?Â?thique en toc,2,4.00

In [48]:
popular_df[popular_df['num_ratings'] >= 250]

,Book-Title,num_ratings,avg_ratings
727,1984,259,4.393822
778,1st to Die: A Novel,469,3.616205
997,2nd Chance,323,3.374613
1669,A Bend in the Road,313,3.226837
3817,A Heartbreaking Work of Staggering Genius,269,3.501859
...,...,...,...
223133,Whispers,267,2.217228
223338,White Oleander : A Novel,353,3.546742
223339,White Oleander : A Novel (Oprah's Book Club),327,3.785933
224193,Wicked: The Life and Times of the Wicked Witch...,286,3.678322
224395,Wild Animus,2263,1.032700

In [49]:
popular_df[popular_df['num_ratings'] >= 250].sort_values('avg_ratings', ascending=False)

,Book-Title,num_ratings,avg_ratings
76830,Harry Potter and the Goblet of Fire (Book 4),346,5.945087
76842,Harry Potter and the Prisoner of Azkaban (Book 3),380,5.884211
76834,Harry Potter and the Order of the Phoenix (Boo...,316,5.544304
76822,Harry Potter and the Chamber of Secrets (Book 2),501,5.177645
182892,The Hobbit : The Enchanting Prelude to The Lor...,261,4.969349
...,...,...,...
50131,Disclosure,291,2.436426
136837,Presumed Innocent,270,2.277778
223133,Whispers,267,2.217228
90154,Isle of Dogs,258,1.864341
224395,Wild Animus,2263,1.032700

In [50]:
popular_df = popular_df[popular_df['num_ratings'] >= 250].sort_values('avg_ratings', ascending=False).head(50)

In [51]:
popular_df

,Book-Title,num_ratings,avg_ratings
76830,Harry Potter and the Goblet of Fire (Book 4),346,5.945087
76842,Harry Potter and the Prisoner of Azkaban (Book 3),380,5.884211
76834,Harry Potter and the Order of the Phoenix (Boo...,316,5.544304
76822,Harry Potter and the Chamber of Secrets (Book 2),501,5.177645
182892,The Hobbit : The Enchanting Prelude to The Lor...,261,4.969349
76853,Harry Potter and the Sorcerer's Stone (Harry P...,519,4.938343
178857,The Fellowship of the Ring (The Lord of the Ri...,340,4.885294
209806,To Kill a Mockingbird,463,4.684665
175236,The Da Vinci Code,828,4.679952
172364,The Catcher in the Rye,401,4.615960
197170,The Secret Life of Bees,704,4.558239
179343,The Five People You Meet in Heaven,392,4.543367
187414,The Lovely Bones: A Novel,1164,4.457045
727,1984,259,4.393822
182870,The Hitchhiker's Guide to the Galaxy,252,4.361111
161045,Stupid White Men ...and Other Sorry Excuses fo...,264,4.337121
195141,The Red Tent (Bestselling Backlist),668,4.326347
213071,"Tuesdays with Morrie: An Old Man, a Young Man,...",437,4.274600
123500,Nickel and Dimed: On (Not) Getting By in America,303,4.244224
61069,Fahrenheit 451,372,4.239247
71406,Girl with a Pearl Earring,486,4.197531
62080,Fast Food Nation: The Dark Side of the All-Ame...,285,4.133333
72926,Good in Bed,456,4.127193
129957,Outlander,262,4.087786
222878,Where the Heart Is (Oprah's Book Club (Paperba...,527,4.070209
148937,Seabiscuit: An American Legend,257,4.066148
168806,The Bean Trees,365,4.032877
103090,Life of Pi,597,4.015075
101001,Left Behind: A Novel of the Earth's Last Days ...,296,3.972973
173443,The Color Purple,289,3.972318
8100,ANGELA'S ASHES,253,3.964427
154258,Skipping Christmas,292,3.934932
180928,"The Golden Compass (His Dark Materials, Book 1)",302,3.927152
12159,American Gods,271,3.896679
209426,Timeline,512,3.857422
150884,Seven Up (A Stephanie Plum Novel),255,3.827451
76492,Hard Eight : A Stephanie Plum Novel (A Stephan...,252,3.821429
5438,A Prayer for Owen Meany,380,3.818421
13782,Angels &amp; Demons,616,3.788961
223339,White Oleander : A Novel (Oprah's Book Club),327,3.785933
202490,"The Vampire Lestat (Vampire Chronicles, Book II)",271,3.756458
162364,Suzanne's Diary for Nicholas,413,3.738499
112882,Me Talk Pretty One Day,426,3.727700
128390,One for the Money (Stephanie Plum Novels (Pape...,269,3.706320
224193,Wicked: The Life and Times of the Wicked Witch...,286,3.678322
20806,Bel Canto: A Novel,319,3.664577
37145,Confessions of a Shopaholic (Summer Display Op...,312,3.663462
115636,Misery,260,3.646154
193383,The Poisonwood Bible: A Novel,455,3.639560
57550,Empire Falls,368,3.635870

In [52]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title', 'Book-Author','Image-URL-M','num_ratings','avg_ratings']]

In [53]:
popular_df.shape

(50, 5)

In [54]:
popular_df
popular_df['Image-URL-M'][0]

'http://images.amazon.com/images/P/0439139597.01.MZZZZZZZ.jpg'

## COLLABORATIVE FILTERING BASED RECOMMENDER SYSTEM

In [55]:
x= ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
x[x] #Boolean indexing to get true values
regular_users = x[x].index

In [56]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
941100,250764,451410777,0,Sleep Tight (Onyx Book),Anne Frasier,2003,Onyx Books,http://images.amazon.com/images/P/0451410777.0...,http://images.amazon.com/images/P/0451410777.0...,http://images.amazon.com/images/P/0451410777.0...
941101,250764,452264464,8,Beloved (Plume Contemporary Fiction),Toni Morrison,1994,Plume,http://images.amazon.com/images/P/0452264464.0...,http://images.amazon.com/images/P/0452264464.0...,http://images.amazon.com/images/P/0452264464.0...
941102,250764,048623715X,0,Glamorous Movie Stars of the Thirties: Paper D...,Tom Tierney,1982,Dover Publications,http://images.amazon.com/images/P/048623715X.0...,http://images.amazon.com/images/P/048623715X.0...,http://images.amazon.com/images/P/048623715X.0...
941103,250764,486256588,0,Schiaparelli Fashion Review: Paper Dolls in Fu...,Tom Tierney,1988,Dover Publications,http://images.amazon.com/images/P/0486256588.0...,http://images.amazon.com/images/P/0486256588.0...,http://images.amazon.com/images/P/0486256588.0...
941104,250764,515069434,0,Lady Laughing Eyes (To Have and to Hold),Lee Damon,1984,Jove Books,http://images.amazon.com/images/P/0515069434.0...,http://images.amazon.com/images/P/0515069434.0...,http://images.amazon.com/images/P/0515069434.0...

In [57]:
filtered_ratings = ratings_with_name[ratings_with_name['User-ID'].isin(regular_users)]

In [58]:
y = filtered_ratings.groupby('Book-Title').count()['Book-Rating'] >= 50
famous_books = y[y].index

In [59]:
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Moon', 'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wuthering Heights', 'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=603)

In [60]:
final_ratings = filtered_ratings[filtered_ratings['Book-Title'].isin(famous_books)]

In [61]:
final_ratings.drop_duplicates()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1153,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1166,277427,60930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...,http://images.amazon.com/images/P/0060930535.0...
1168,277427,60934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...,http://images.amazon.com/images/P/0060934417.0...
1171,277427,61009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...,http://images.amazon.com/images/P/0061009059.0...
1177,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...,http://images.amazon.com/images/P/006440188X.0...
...,...,...,...,...,...,...,...,...,...,...
941058,250764,446364673,0,The Gift,Kirk Douglas,1993,Warner Books,http://images.amazon.com/images/P/0446364673.0...,http://images.amazon.com/images/P/0446364673.0...,http://images.amazon.com/images/P/0446364673.0...
941079,250764,449907481,0,A Thousand Acres (Ballantine Reader's Circle),JANE SMILEY,1992,Ballantine Books,http://images.amazon.com/images/P/0449907481.0...,http://images.amazon.com/images/P/0449907481.0...,http://images.amazon.com/images/P/0449907481.0...
941086,250764,451180410,0,Mortal Fear,Greg Iles,1998,Signet Book,http://images.amazon.com/images/P/0451180410.0...,http://images.amazon.com/images/P/0451180410.0...,http://images.amazon.com/images/P/0451180410.0...
941088,250764,451191013,0,The Regulators,Stephen King,2002,Signet Book,http://images.amazon.com/images/P/0451191013.0...,http://images.amazon.com/images/P/0451191013.0...,http://images.amazon.com/images/P/0451191013.0...
941090,250764,451192001,0,How Stella Got Her Groove Back,Terry McMillan,1997,Signet Book,http://images.amazon.com/images/P/0451192001.0...,http://images.amazon.com/images/P/0451192001.0...,http://images.amazon.com/images/P/0451192001.0...

In [62]:
pt = final_ratings.pivot_table(index='Book-Title', columns = 'User-ID', values = 'Book-Rating')

In [63]:
pt.shape

(603, 735)

In [64]:
pt.fillna(0, inplace=True)

In [65]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,249111,249628,249862,249894,250184,250405,250764,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [66]:
#%pip install scikit-learn

In [67]:
from sklearn.metrics.pairwise import cosine_similarity

In [68]:
similarity_scores = cosine_similarity(pt)

In [69]:
def recommend(book_name):
    # index fetch
    index = np.where(pt.index == book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])), key=lambda x:x[1], reverse=True)[1:6]

    for i in similar_items:
        print([pt.index[i[0]]])

In [70]:
recommend('The Notebook')

['A Walk to Remember']
['The Rescue']
['The Guardian']
['Toxin']
['The Five People You Meet in Heaven']

In [71]:
np.where(pt.index == 'Zoya')[0][0]

np.int64(601)

In [72]:
sorted(list(enumerate(similarity_scores[0])), key=lambda x:x[1], reverse=True)[1:6]

[(41, np.float64(0.27779439320159416)),
 (70, np.float64(0.2660586000369668)),
 (541, np.float64(0.2506295364129756)),
 (459, np.float64(0.23786512783485833)),
 (147, np.float64(0.234784541598818))]

In [73]:
similarity_scores.shape

(603, 603)

In [74]:
similarity_scores[0]

array([1.        , 0.11013674, 0.0127091 , 0.        , 0.05618727,
       0.03068486, 0.0874928 , 0.15837741, 0.03352553, 0.03769765,
       0.07734131, 0.02289102, 0.10711257, 0.08534426, 0.11769018,
       0.0557728 , 0.02587927, 0.12651909, 0.        , 0.14733114,
       0.08388437, 0.07732577, 0.09389112, 0.        , 0.07642162,
       0.14517437, 0.12847808, 0.01638712, 0.09117911, 0.05011953,
       0.01653141, 0.10104308, 0.01975371, 0.0268319 , 0.0885619 ,
       0.12161054, 0.06009405, 0.08965023, 0.01517732, 0.09520085,
       0.05637857, 0.27779439, 0.10570014, 0.01038525, 0.09208417,
       0.        , 0.04592574, 0.02005129, 0.        , 0.06136685,
       0.00604602, 0.08465384, 0.05775924, 0.1985691 , 0.        ,
       0.01346916, 0.03154015, 0.04679173, 0.08915014, 0.        ,
       0.13920242, 0.06799777, 0.        , 0.11604696, 0.03040797,
       0.05247255, 0.07067691, 0.12127148, 0.03442769, 0.01540805,
       0.2660586 , 0.        , 0.10733528, 0.09150259, 0.03182853,
       0.07643576, 0.        , 0.17184433, 0.03371911, 0.01161106,
       0.02315884, 0.03079811, 0.02354807, 0.        , 0.05087004,
       0.06517425, 0.01409486, 0.05608625, 0.05868766, 0.07098951,
       0.02293094, 0.08172074, 0.01834054, 0.0169571 , 0.11557531,
       0.17479853, 0.15946528, 0.06411221, 0.08866155, 0.0626556 ,
       0.08506674, 0.04207216, 0.06349231, 0.03624645, 0.0394867 ,
       0.0515041 , 0.01162238, 0.01806033, 0.07694006, 0.        ,
       0.        , 0.        , 0.02952644, 0.03407569, 0.10252871,
       0.        , 0.02478026, 0.02960888, 0.        , 0.        ,
       0.02009356, 0.03227679, 0.02317792, 0.11375882, 0.02965917,
       0.11405365, 0.10174488, 0.15275357, 0.01570753, 0.08932473,
       0.00906821, 0.05374814, 0.        , 0.01411866, 0.04114861,
       0.0768598 , 0.01338666, 0.02086884, 0.01613124, 0.1546981 ,
       0.06818861, 0.02953902, 0.        , 0.15658   , 0.03849654,
       0.        , 0.02017606, 0.23478454, 0.01558074, 0.1028289 ,
       0.02347791, 0.02193227, 0.05550778, 0.08387877, 0.01166632,
       0.03976337, 0.06161668, 0.        , 0.15448878, 0.02144119,
       0.10648242, 0.10067234, 0.06794143, 0.09304639, 0.09565454,
       0.02528702, 0.19117431, 0.05285139, 0.05397639, 0.11401113,
       0.10766679, 0.06384661, 0.05746483, 0.03770721, 0.        ,
       0.09681127, 0.06974098, 0.05509775, 0.13239972, 0.09230146,
       0.13461528, 0.09029421, 0.08562932, 0.        , 0.03902994,
       0.16543679, 0.04070925, 0.07927592, 0.10331757, 0.05770931,
       0.07592049, 0.08144431, 0.03570785, 0.01673179, 0.02090211,
       0.02532225, 0.        , 0.02284261, 0.06995879, 0.0223453 ,
       0.12655653, 0.0883629 , 0.02240905, 0.        , 0.04949054,
       0.08947746, 0.14475609, 0.01559893, 0.14427518, 0.0791893 ,
       0.12409571, 0.05575706, 0.01726867, 0.02706376, 0.04950139,
       0.02296101, 0.10979448, 0.14486065, 0.        , 0.06064408,
       0.01949719, 0.        , 0.05285987, 0.03739746, 0.18128958,
       0.09937455, 0.071373  , 0.03070886, 0.        , 0.09728841,
       0.08424482, 0.05107612, 0.01556233, 0.02463426, 0.096999  ,
       0.00935743, 0.03067719, 0.02125824, 0.02481376, 0.13233443,
       0.        , 0.02551678, 0.07016206, 0.        , 0.06478974,
       0.15111644, 0.02202624, 0.01295949, 0.04557405, 0.03209491,
       0.03117223, 0.0702737 , 0.0890494 , 0.11881102, 0.12313034,
       0.13819948, 0.10443096, 0.18159618, 0.07644963, 0.        ,
       0.09647727, 0.01104658, 0.        , 0.09200764, 0.04273388,
       0.20765297, 0.01778552, 0.03418939, 0.03482116, 0.10740511,
       0.10935219, 0.01808751, 0.12999563, 0.10630975, 0.03761696,
       0.08095393, 0.0912874 , 0.01954162, 0.02238144, 0.17662236,
       0.        , 0.        , 0.01175271, 0.02213071, 0.        ,
       0.0213464 , 0.01344947, 0.01033967, 0.01682586, 0.06867172,
       0.10175725, 0.06324393, 0.06791346, 0.        , 0.02238144,
       0.08062078, 0.18957795, 0.08078216, 0.        , 0.019556  ,
       0.12187193, 0.10768412, 0.09145874, 0.09338304, 0.11716634,
       0.        , 0.02423048, 0.06524361, 0.01982421, 0.06389736,
       0.02227229, 0.10806625, 0.13970062, 0.        , 0.07088441,
       0.10028578, 0.        , 0.02954704, 0.01706041, 0.06420676,
       0.02155071, 0.0185177 , 0.12711729, 0.06648338, 0.14811756,
       0.        , 0.0729493 , 0.        , 0.05922611, 0.02436918,
       0.00903974, 0.07335084, 0.1115739 , 0.02685175, 0.        ,
       0.0951636 , 0.01777824, 0.10711   , 0.        , 0.01878098,
       0.        , 0.06028069, 0.1783604 , 0.14322371, 0.13131152,
       0.02393919, 0.02042633, 0.01186345, 0.02739974, 0.01010278,
       0.08977952, 0.02001225, 0.07220711, 0.02450074, 0.13180214,
       0.10277325, 0.06532245, 0.02963342, 0.04625648, 0.05552673,
       0.00900028, 0.10398757, 0.1101768 , 0.        , 0.13472424,
       0.01912399, 0.02129699, 0.11972841, 0.1339112 , 0.1000778 ,
       0.09676429, 0.06101924, 0.08257237, 0.05147342, 0.06991718,
       0.0252089 , 0.07104829, 0.020678  , 0.04669322, 0.        ,
       0.0561446 , 0.01418692, 0.        , 0.05225592, 0.08932969,
       0.10822762, 0.01902994, 0.10196294, 0.08939814, 0.0039979 ,
       0.06027318, 0.05974804, 0.        , 0.06422979, 0.11101507,
       0.        , 0.08157177, 0.        , 0.14327716, 0.05717786,
       0.17391754, 0.01892256, 0.05776177, 0.        , 0.0847733 ,
       0.14174673, 0.00620667, 0.07580992, 0.05579718, 0.06314326,
       0.05678602, 0.20711302, 0.11815113, 0.06957948, 0.06580312,
       0.        , 0.        , 0.11815872, 0.04971139, 0.02132316,
       0.        , 0.01370312, 0.22356342, 0.06494586, 0.04535604,
       0.0286579 , 0.07805605, 0.05708181, 0.07254446, 0.01683487,
       0.02896014, 0.02151889, 0.1442931 , 0.12512194, 0.09426108,
       0.10686602, 0.12613202, 0.07740234, 0.04879375, 0.        ,
       0.22552206, 0.02745658, 0.06160345, 0.2126727 , 0.06496271,
       0.06597806, 0.02312855, 0.02781352, 0.06873563, 0.08121964,
       0.08922442, 0.17958365, 0.08483338, 0.01233129, 0.09343123,
       0.19255469, 0.08763217, 0.02021059, 0.1824324 , 0.23786513,
       0.19734887, 0.061184  , 0.04248742, 0.07520489, 0.16088824,
       0.23256741, 0.2020424 , 0.02460015, 0.15969038, 0.01705372,
       0.05448494, 0.13242166, 0.15195163, 0.08802382, 0.02630335,
       0.13305141, 0.01284413, 0.07574134, 0.03517224, 0.07394634,
       0.02387728, 0.1605071 , 0.0965165 , 0.        , 0.        ,
       0.02001156, 0.10277284, 0.05000965, 0.13396446, 0.01649152,
       0.11443423, 0.06068084, 0.06595403, 0.06990948, 0.1517916 ,
       0.        , 0.04768003, 0.02421716, 0.18270943, 0.01979733,
       0.16871652, 0.        , 0.06733244, 0.08626422, 0.07783425,
       0.06729079, 0.07787376, 0.17606666, 0.02759217, 0.01988047,
       0.05589108, 0.05196132, 0.        , 0.12064258, 0.08639837,
       0.14208058, 0.02370919, 0.07004159, 0.02260363, 0.04869051,
       0.10813081, 0.1236551 , 0.02950629, 0.00178548, 0.10147988,
       0.08492708, 0.02258122, 0.01714265, 0.02225656, 0.10491354,
       0.0195985 , 0.19675855, 0.06210377, 0.2150064 , 0.06505999,
       0.01551924, 0.10466572, 0.01174553, 0.11906083, 0.07986949,
       0.08877812, 0.25062954, 0.01146213, 0.04958739, 0.15782083,
       0.        , 0.14387479, 0.06964238, 0.15130125, 0.01833375,
       0.09773047, 0.05653404, 0.19187723, 0.11996571, 0.04491848,
       0.03943185, 0.02532121, 0.08063968, 0.03740485, 0.03091471,
       0.02669956, 0.04587031, 0.15380592, 0.13777057, 0.01622923,
       0.03145614, 0.02448826, 0.07597703, 0.09192314, 0.1674994 ,
       0.07841535, 0.01228968, 0.11520946, 0.06453425, 0.10048626,
       0.14899564, 0.06348371, 0.        , 0.02205355, 0.        ,
       0.02040901, 0.        , 0.13764215, 0.09189302, 0.09637498,
       0.00823495, 0.0837076 , 0.        , 0.04392382, 0.08922689,
       0.08325867, 0.07565973, 0.01701   , 0.03838607, 0.05747133,
       0.01171933, 0.01117662, 0.01049377, 0.0619086 , 0.01818944,
       0.12447747, 0.07552261, 0.04645965])

In [75]:
import pickle
pickle.dump(popular_df, open('popular.pkl', 'wb'))

In [76]:
popular_df

,Book-Title,Book-Author,Image-URL-M,num_ratings,avg_ratings
0,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,346,5.945087
2,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,380,5.884211
5,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,316,5.544304
9,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,501,5.177645
12,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,261,4.969349
13,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,519,4.938343
15,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,340,4.885294
24,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,463,4.684665
32,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,828,4.679952
38,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,401,4.615960
45,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,704,4.558239
51,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,392,4.543367
53,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1164,4.457045
54,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,259,4.393822
65,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,252,4.361111
74,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,264,4.337121
75,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,668,4.326347
76,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,437,4.274600
79,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,303,4.244224
81,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,372,4.239247
94,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,486,4.197531
95,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,285,4.133333
96,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,456,4.127193
98,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,262,4.087786
104,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,527,4.070209
105,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,257,4.066148
107,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,365,4.032877
110,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,597,4.015075
114,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,296,3.972973
116,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,289,3.972318
122,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,253,3.964427
124,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,292,3.934932
130,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,302,3.927152
138,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,271,3.896679
139,Timeline,MICHAEL CRICHTON,http://images.amazon.com/images/P/0345417623.0...,512,3.857422
146,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,255,3.827451
148,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,252,3.821429
153,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,380,3.818421
155,Angels &amp; Demons,Dan Brown,http://images.amazon.com/images/P/0671027360.0...,616,3.788961
160,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,327,3.785933
161,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,271,3.756458
162,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,413,3.738499
166,Me Talk Pretty One Day,David Sedaris,http://images.amazon.com/images/P/0316776963.0...,426,3.727700
170,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,http://images.amazon.com/images/P/0061009059.0...,269,3.706320
171,Wicked: The Life and Times of the Wicked Witch...,Gregory Maguire,http://images.amazon.com/images/P/0060987103.0...,286,3.678322
172,Bel Canto: A Novel,Ann Patchett,http://images.amazon.com/images/P/0060934417.0...,319,3.664577
173,Confessions of a Shopaholic (Summer Display Op...,SOPHIE KINSELLA,http://images.amazon.com/images/P/0385335482.0...,312,3.663462
174,Misery,Stephen King,http://images.amazon.com/images/P/0451153553.0...,260,3.646154
182,The Poisonwood Bible: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060930535.0...,455,3.639560
183,Empire Falls,Richard Russo,http://images.amazon.com/images/P/0375726403.0...,368,3.635870